INSERT

/*INSERT INTO artists(name)
VALUES ('Michael Jackson');*/

/*INSERT INTO albums (ArtistId ,Title) 
VALUES ('276', 'Thriller (album) (1982)');*/

/*INSERT INTO tracks(name, AlbumId, MediaTypeId, Milliseconds, UnitPrice)
VALUES ('Billie Jean','348','5','342657','1.99'),('Human Nature','348', '5','357844','1.99'),('Baby Be Mine','348', '5','346573','1.99');*/

UPDATE

/*UPDATE tracks 
set GenreId = 9, MediaTypeId = 2, Composer = "Michael Jackson", Bytes = 1245656
where TrackId = 3504;
    
UPDATE tracks 
set GenreId = 9, MediaTypeId = 1, Composer = "Michael Jackson", Bytes = 1436455
where TrackId = 3505;

UPDATE tracks 
set GenreId = 9, MediaTypeId = 4, Composer = "Michael Jackson", Bytes = 1116745
where TrackId = 3506;*/

DELETE

/*DELETE FROM tracks
WHERE AlbumId = 348;*/

/*DELETE FROM albums
WHERE AlbumId = 348;*/

/*DELETE from artists
where name = "Michael Jackson";*/


